### ISSUE TITLE
Faust + esp32 = awesomeness! 

### ISSUE THREAD

**Issue by NikolajAndersson** [rmichon/esp32#1]
Hi Romain! 

What is the status of this? It looks super promising! I am playing around with the esp32 and I would love to get some faust in the mix!

Do you have some documentation on how to get this up and running? Or anywhere to start? 
and which type of dev board did you use?

Cheers, 
Nikolaj

**Comment by rmichon** [comment]
Hey Nikolaj,

I'm currently working on this and I hope to have a working prototype by the end of the week. In the meantime, the following contains a working projects based on a code generated by Faust and used in the Arduino IDE: https://github.com/rmichon/esp32/tree/master/ttgo-t-audio/arduino/ttgo. Similarly, the following: https://github.com/rmichon/esp32/tree/master/ttgo-t-audio/native/ttgo contains a native project in C++ (not arduino-based).

I'll let you know when I'm done merging this to the Faust repo. 

Cheers,

Romain

**Comment by NikolajAndersson** [comment]
Great! and thanks for the quick answer Romain! 
I will try it out in one of the following weeks :) 

Cheers!
